name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install AsciiDoctor
      run: sudo gem install asciidoctor asciidoctor-diagram asciidoctor-html5s

    - name: Run Hugo
      run: |
        alias asciidoctor="asciidoctor --attribute=experimental=true --attribute=icons=font"
        hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        publish_branch: gh-pages

    # - uses: sarisia/actions-status-discord@v1
    #   if: always()
    #   with:
    #     webhook: ${{ secrets.DISCORD_WEBHOOK }}
    #     title: "Mise à jour du site"
    #     description: "La nouvelle version sera disponible dans quelques minutes sur https://lartdelachance.github.io/"
    #     nodetail: true
